name: Deploy to AWS (on merge to main)

on:
  push:
    branches:
      - main  # Triggers only when code is pushed/merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      # - name: Apply Terraform
      #   working-directory: terraform
      #   run: terraform apply -auto-approve
      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
